"""Format smell reports as Markdown."""

from __future__ import annotations

from html import escape
from pathlib import Path

from metala.domain.smells import SmellKind, SourceSmellReport

_SEVERITY_ORDER = {"error": 0, "warning": 1, "info": 2, "note": 3}

_BADGE_MD: dict[str, str] = {
    "error": "🔴",
    "warning": "🟡",
    "info": "🔵",
    "note": "🟢",
}

_EMOJI: dict[str, str] = {
    "long_function": "📏",
    "long_parameter_list": "📦",
    "large_class": "🏗️",
    "deep_nesting": "🕳️",
    "complex_flow": "🌀",
    "magic_number": "🔢",
    "excessive_locals": "🗂️",
    "unused_parameter": "🔕",
    "switch_statement": "🔀",
    "message_chain": "🔗",
    "data_clump": "🧩",
    "feature_envy": "😒",
    "primitive_obsession": "🪨",
    "middle_man": "🤝",
    "speculative_generality": "🔮",
    "divergent_change": "📊",
    "shotgun_surgery": "💥",
    "temporary_field": "⏳",
    "refused_bequest": "👑",
    "comment_density": "💬",
    "divergent_branch": "⚡",
    "resource_overload": "🔋",
    "atomic_contention": "⚛️",
}


def format_file(report: SourceSmellReport) -> str:
    smells = sorted(
        report.smells,
        key=lambda s: (
            _SEVERITY_ORDER.get(getattr(s, "severity", "warning"), 99),
            s.line,
            s.column,
        ),
    )
    total = len(smells)
    location = report.source_location

    # ── danger line ────────────────────────────────────────────────────────
    if total == 0:
        danger = "🟢 Clean"
    elif total <= 3:
        danger = "🟢 Low"
    elif total <= 8:
        danger = "🟡 Medium"
    elif total <= 20:
        danger = "🔴 High"
    else:
        danger = "☠️ Critical"

    lines: list[str] = [
        "# \U0001f4ac Code Smell Report",
        "",
        "**File:** `" + location + "`",
        "**Status:** "
        + danger
        + " \u2014 "
        + str(total)
        + " smell"
        + ("" if total == 1 else "s")
        + " detected",
        "",
    ]

    if not smells:
        lines.append("_No smells found._")
        return "\n".join(lines) + "\n"

    # ── severity summary ───────────────────────────────────────────────────
    sev_counts: dict[str, int] = {}
    for s in smells:
        sev = getattr(s, "severity", "warning")
        sev_counts[sev] = sev_counts.get(sev, 0) + 1

    lines.append("## Summary")
    lines.append("")
    for sev in ("error", "warning", "info", "note"):
        cnt = sev_counts.get(sev, 0)
        if cnt == 0:
            continue
        badge = _BADGE_MD.get(sev, "")
        lines.append("- " + badge + " **" + sev.title() + ":** " + str(cnt))
    lines.append("")

    # ── detailed table ─────────────────────────────────────────────────────
    lines.append("## Findings")
    lines.append("")
    lines.append("| # | | Smell | Line | Message |")
    lines.append("|---:|:---:|:---|-----:|:---|")

    for idx, s in enumerate(smells, 1):
        k = s.kind.value if isinstance(s.kind, SmellKind) else str(s.kind)
        emoji = _EMOJI.get(k, "\u26a0\ufe0f")
        display = k.replace("_", " ").title()
        sev = getattr(s, "severity", "warning")
        badge = _BADGE_MD.get(sev, "")
        msg = s.message
        if len(msg) > 90:
            msg = msg[:87] + "\u2026"
        lines.append(
            "| "
            + str(idx)
            + " | "
            + badge
            + " | "
            + emoji
            + " **"
            + display
            + "** | "
            + str(s.line)
            + " | "
            + msg
            + " |"
        )

    lines += ["", "---", "*Generated by metala*"]

    return "\n".join(lines) + "\n"


def format_directory_bundle(bundle) -> str:
    lines: list[str] = [
        "# \U0001f4ac Directory Smell Index",
        "",
        "**Root:** `" + bundle.root_path + "`",
        "",
    ]

    by_severity: dict[str, int] = {}
    for r in bundle.reports:
        for s in r.smells:
            sev = getattr(s, "severity", "warning")
            by_severity[sev] = by_severity.get(sev, 0) + 1
    total = bundle.total_smell_count

    if not bundle.reports:
        lines.append("_No Metal files found._")
        return "\n".join(lines) + "\n"

    if total == 0:
        lines.append("\U0001f7e2 **Clean** \u2014 no smells detected in any file.")
    else:
        parts = []
        for sev in ("error", "warning", "info", "note"):
            cnt = by_severity.get(sev, 0)
            if cnt > 0:
                badge = _BADGE_MD.get(sev, "")
                parts.append(badge + " **" + sev.title() + ":** " + str(cnt))
        lines.append(
            "Captured **"
            + str(total)
            + " smell"
            + ("" if total == 1 else "s")
            + "** across "
            + str(len(bundle.reports))
            + " file(s)."
        )
        if parts:
            lines.append(" &nbsp; ".join(parts))

    lines += [
        "",
        "_Scanned " + str(len(bundle.reports)) + " file(s)._",
        "",
        "| File | Smells |",
        "|------|-------:|",
    ]

    for r in sorted(bundle.reports, key=lambda x: -x.smell_count):
        fname = Path(r.source_location).name
        bare = fname.replace(".metal", "")
        if r.smell_count > 0:
            lines.append("| `" + bare + "` | **" + str(r.smell_count) + "** |")
        else:
            lines.append("| `" + bare + "` | *0* |")

    lines += ["", "---", "*Generated by metala*"]

    return "\n".join(lines) + "\n"
